### ISSUE TITLE
Zimbabwe

### ISSUE THREAD

**Issue by daffster** [lefranz/geneva-dictators#10]
You might want to add Zimbabwe to that list.

Z-WPF or any plane Z-WP[A-N] going into Geneva is suspicious.

**Comment by jpilet** [comment]
Do you have any source mentioning those planes?

Zimbabwe is indeed classified as an authoritarian regime in the democracy index.

**Comment by daffster** [comment]
https://www.planespotters.net/airline/Air-Zimbabwe lists the current Air Zimbabwe Fleet.

Whenever Mugabe flies, the flight is designated UM1.
https://www.flightradar24.com/data/flights/um1

Historically, this is on aircraft Z-WPF

Since Air Zimbabwe doesn't fly anywhere near Europe, any flight from Air Zimbabwe in Geneva is a "chartered" flight by the President.

**Comment by qligier** [comment]
> The President of Zimbabwe travels in a chartered Air Zimbabwe Boeing 767-200ER aircraft, which is part of the national airline's fleet. Occasionally, the president will share the plane with commercial passengers on scheduled flights. 

[Wikipedia: Air transports of heads of state and government](https://en.wikipedia.org/wiki/Air_transports_of_heads_of_state_and_government#Zimbabwe)

If that's true, we shouldn't spot him in GVA in something else than a Boeing 767-200ER, as scheduled flights doesn't come in GVA. Air Zimbabwe has two Boeing 767-200ER, registered as Z-WPE and Z-WPF ([PlaneSpotters](https://www.planespotters.net/airline/Air-Zimbabwe)). So Z-WPF should really be added to the list. Not so sure for other planes.

Anyway, the other planes seem to be Z-WPA, Z-WPB, Z-WPC, Z-WPN and Z-WPM:
- [AirFrames](http://www.airframes.org/fleet/azw) has Z-WP[ABCEF];
- [PlaneFinder](https://planefinder.net/data/airline/UM) has Z-WP[ABCEFN];
- [PlaneSpotters](https://www.planespotters.net/airline/Air-Zimbabwe) has Z-WP[ABCEFNM].

**Comment by jpilet** [comment]
I'll try to see if I can get the UM1 tag.

http://www.lemonde.fr/afrique/article/2016/09/16/zimbabwe-pour-savoir-si-robert-mugabe-est-vivant-tapez-um1-sur-votre-smartphone_4998779_3212.html

**Comment by lefranz** [comment]
added Z-WPE and Z-WPF
