### ISSUE TITLE
specify flight data source

### ISSUE THREAD

**Issue by sjiekak** [lefranz/geneva-dictators#11]
The flight data source is present in the source code, but there is no mention of it in the readme.

**Comment by metc** [comment]
It's true. If you look [at the source code](https://github.com/lefranz/geneva-dictators/blob/master/aragge.js#L15), you can see that the data are coming from http://aragge.ch/, but there is no information in the Readme file. 

What I would also like to know is where this script is running and at which frequency the data are updated ?

**Comment by qligier** [comment]
[The source code](https://github.com/lefranz/geneva-dictators/blob/master/aragge.js#L21) seems to indicate that the data are updated once an hour.
