### ISSUE TITLE
Brazil

### ISSUE THREAD

**Issue by gcb** [lefranz/geneva-dictators#6]
Brazil has a non-elected "president" nowadays.

> Airbus A319, with tail number 2101. It was designated by the Brazilian Air Force as VC-1A, and officially christened as the "Santos-Dumont"  -- https://en.wikipedia.org/wiki/Brazilian_Air_Force_One

**Comment by jpilet** [comment]
Brazil is listed as "Flawed democracy" in the democracy index. So for now we will not track VC-1A.
Thank you for your contribution anyway.
